baseurl: ""

title      : evo Bond Legacy - Bond Origination & Home Loans Expert in Cape Town
email      : thea@bondlegacy.co.za
description: Contact Thea from evo Bond Legacy to help you with your home loan. We are seasoned property professionals and specialize in mortgages and property finance with years of experience. Our experience ranges from sales to finance and out focus is bonds, homeloans and origination. evo Bond Legacy is committed to excellent client service, building long-term relationships.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-B3CFYG546T

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo Bond Legacy Logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Home Loans

company: evo Bond Legacy 

url: https://evohomeloans.co.za/bond-originators/pretoria/

address: 417 Braam Pretorius Street, Magalieskruin, Pretoria
